version: "2.2"
services:
  neo4j_path:
    image: neo4j
    ports:
      - "7475:7474"
      - "7688:7687"
    volumes:
      - '$PWD/lineage_server/neo4j/logs_path:/logs'
      - '$PWD/lineage_server/neo4j/data_path:/data'
      - '$PWD/lineage_server/neo4j/plugins_path:/plugins'
      - '$PWD/lineage_server/neo4j/conf_path:/conf'
    ulimits:
      nproc: 65535
      nofile:
        soft: 40000
        hard: 40000
    environment:
      NEO4J_AUTH: "none"
  neo4j_got:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - '$PWD/lineage_server/neo4j/logs:/logs'
      - '$PWD/lineage_server/neo4j/data:/data'
      - '$PWD/lineage_server/neo4j/plugins:/plugins'
      - '$PWD/lineage_server/neo4j/conf:/conf'
    ulimits:
      nproc: 65535
      nofile:
        soft: 40000
        hard: 40000
    environment:
      NEO4J_AUTH: "none"
  neo4j_dblp:
    image: neo4j
    ports:
      - "7476:7474"
      - "7689:7687"
    volumes:
      - '$PWD/lineage_server/neo4j/logs_dblp:/logs'
      - '$PWD/lineage_server/neo4j/data_dblp:/data'
      - '$PWD/lineage_server/neo4j/plugins_dblp:/plugins'
      - '$PWD/lineage_server/neo4j/conf_dblp:/conf'
    ulimits:
      nproc: 65535
      nofile:
        soft: 40000
        hard: 40000
    environment:
      NEO4J_AUTH: "none"