version: '2.0'
services:
  neo4j_path:
    image: neo4j
    ports:
      - "7475:7474"
      - "7688:7687"
    volumes:
      - '$PWD/lineage_server/neo4j/logs_path:/logs'
      - '$PWD/lineage_server/neo4j/data_path:/data'
      - '$PWD/lineage_server/neo4j/plugins_path:/plugins'
      - '$PWD/lineage_server/neo4j/conf_path:/conf'
    ulimits:
      nproc: 65535
      nofile:
        soft: 40000
        hard: 40000
    mem_limit: 1000000000
    environment:
      NEO4J_AUTH: "none"
  neo4j_got:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - '$PWD/lineage_server/neo4j/logs:/logs'
      - '$PWD/lineage_server/neo4j/data:/data'
      - '$PWD/lineage_server/neo4j/plugins:/plugins'
      - '$PWD/lineage_server/neo4j/conf:/conf'
    ulimits:
      nproc: 65535
      nofile:
        soft: 40000
        hard: 40000
    mem_limit: 1000000000
    environment:
      NEO4J_AUTH: "none"
  # neo4j_coauth:
  #   image: neo4j
  #   ports:
  #     - "7476:7474"
  #     - "7689:7687"
  #   # volumes:
  #     # - '$PWD/neo4j/logs:/logs'
  #     # - '$PWD/neo4j/data:/data'
  #     # - '$PWD/neo4j/plugins:/plugins'
  #     # - '$PWD/neo4j/conf:/conf'
  #   environment:
  #     NEO4J_AUTH: "none"